"""Added Form model with foreign key

Revision ID: fba47897649b
Revises: 6e9a2e5fd1b8
Create Date: 2025-02-10 07:58:11.623110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba47897649b'
down_revision = '6e9a2e5fd1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_question_form', 'form', ['form_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_form', type_='foreignkey')
        batch_op.drop_column('form_id')

    # ### end Alembic commands ###
