"""Move answer and evidence to Response model

Revision ID: 2660e2eb3ecd
Revises: d99759b6ea18
Create Date: 2024-07-21 10:04:17.175925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2660e2eb3ecd'
down_revision = 'd99759b6ea18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('answer')
        batch_op.drop_column('evidence')

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('evidence', sa.String(length=256), nullable=True))
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('evidence')
        batch_op.drop_column('answer')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
