"""Update Question model to make id auto, question required, and other fields nullable

Revision ID: d99759b6ea18
Revises: c758e56c8756
Create Date: 2024-07-21 09:02:17.277998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99759b6ea18'
down_revision = 'c758e56c8756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
