"""Add Question model

Revision ID: f312cfb5a0eb
Revises: 567cf5868473
Create Date: 2024-07-16 02:56:51.869467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f312cfb5a0eb'
down_revision = '567cf5868473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.String(length=256), nullable=True),
    sa.Column('parent_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
